name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./backend
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          MONGO_DB_PROBLEMS: ${{ secrets.MONGO_DB_PROBLEMS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PORT: ${{ secrets.PORT }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: MONGODB_URL,MONGO_DB_PROBLEMS,JWT_SECRET,GEMINI_API_KEY,PORT
          script: |
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d \
              --name backend \
              -p 5000:5000 \
              --restart always \
              -e MONGODB_URL="$MONGODB_URL" \
              -e MONGO_DB_PROBLEMS="$MONGO_DB_PROBLEMS" \
              -e JWT_SECRET="$JWT_SECRET" \
              -e GEMINI_API_KEY="$GEMINI_API_KEY" \
              -e PORT="$PORT" \
              ${{ secrets.ECR_REPOSITORY }}:latest